name: Semantic release 

on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.14.0
      - name: Install dependencies
        run: npm install 
      - name: Build app
        run: npm run build 
      - name: Semantic release
        env:
          GITHUB_TOKEN: "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"
          NPM_TOKEN: "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"
        run: npx semantic-release
