name: Semantic release 
"on":
  push:
    branches:
      - main
      - next
      - beta
      - "*.x"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.14.0
      - name: Install dependencies
        run: npm install 
      - name: Build app
        run: npm run build 
      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: "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"
          NPM_TOKEN: "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"
